# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: 'TFC - Apply Run'
description: "Applies a run that is paused waiting for confirmation after a plan."

inputs:
  # global flags
  hostname:
    required: false
    description: "The hostname of a Terraform Enterprise installation, if using Terraform Enterprise. Defaults to HCP Terraform (app.terraform.io) if `TF_HOSTNAME` environment variable is not set."
    default: ""
  token:
    required: false
    description: "The token used to authenticate with HCP Terraform. Defaults to reading `TF_API_TOKEN` environment variable."
    default: ""
  organization:
    required: false
    description: "The name of the organization in HCP Terraform. Defaults to reading `TF_CLOUD_ORGANIZATION` environment variable."
    default: ""
  # required
  run:
    required: true
    description: "The run ID to apply."
  # optional
  comment:
    required: false
    description: "An optional comment about the run."
    default: ""

outputs:
  status:
    description: "The result of the operation. Possible values are `Success`, `Error`, `Timeout` or `Noop`."
  run_id:
    description: "The provided run ID."
  run_status:
    description: "The current status of the HCP Terraform run."

runs:
  using: docker
  image: 'docker://hashicorp/tfci:v1.3.0'
  args:
  - tfci
  ## global flags
  - -hostname=${{ inputs.hostname }}
  - -token=${{ inputs.token }}
  - -organization=${{ inputs.organization }}
  ## command
  - run
  - apply
  - -run=${{ inputs.run }}
  - -comment=${{ inputs.comment }}
